### ISSUE TITLE
Reduce the amount of calls to fetch the original reconciliation targets 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-incubator/reconciler#412] opened 2021-11-15 13:51 UTC
**Description**

Every time [deployManifest](https://github.com/kyma-incubator/reconciler/blob/e1463f15fb40506a23b32f801db9020f8812389e/pkg/reconciler/kubernetes/adapter/adapter.go#L87) function is called the existing runtime objects are fetched mutliple times:

 - in case the target object is of kind `service` - the interceptor will fetch it
 - we fetch it [here](https://github.com/kyma-incubator/reconciler/blob/3767aa1d263e5350bf8e2f1ffa78975404bb9aa1/pkg/reconciler/kubernetes/kubeclient/kubeclient.go#L142) to check if the resource exists.. in case it does, we forget it..not re-use it later in the call stack
 - we fetch it again to check resource version as part of replace logic - [here](https://github.com/kyma-incubator/reconciler/blob/cf2974386ef714e098d43e526a2c4a40bd2f9a48/pkg/reconciler/kubernetes/kubeclient/replace.go#L80)
 
 
**Reasons**

 This is not optimal. we should reduce the amount of calls taking into account amount of reconciliation runs * mutliplied by amount of runtimes on a landscape.

**Comment by tobiscr** [comment] 2021-12-09 16:19
Duplicate of https://github.com/kyma-incubator/reconciler/issues/532

**Closed by tobiscr** 2021-12-09 16:19 UTC
Labels: enhancement, area/reconciler
