### ISSUE TITLE
Handle the situation if target cluster is not reachable while deleting components

### ISSUE THREAD

**Issue by ruanxin** [kyma-incubator/reconciler#1100] opened 2022-05-30 16:40 UTC
Check the summary here: https://github.tools.sap/kyma/backlog/issues/2654#issuecomment-1064333

Brainstorming: find a better way to handle non exisiting cluster so that don't waste capacity of workers.

**Comment by tobiscr** [comment] 2022-05-30 20:15
Duplicate of https://github.com/kyma-incubator/reconciler/issues/980

**Closed by tobiscr** 2022-05-30 20:15 UTC
Labels: kind/bug
