### ISSUE TITLE
Reconciler support for the HorizontalPodAutoscaler configuration

### ISSUE THREAD

**Issue by cnvergence** [kyma-incubator/reconciler#536] opened 2021-12-07 09:45 UTC
**Description**
As described in the [issue](https://github.com/kyma-incubator/reconciler/issues/524), the reconciler and the autoscaler are fighting over the replicas field.
Reconciler should detect when a HorizontalPodAutoscaler is created and do not overwrite the replicas setting on the deployment.

**Reasons**
Currently HorizontalPodAutoscaler is not supported.

**Comment by varbanv** [comment] 2021-12-07 14:09
Duplicate of https://github.com/kyma-incubator/reconciler/issues/524

**Closed by varbanv** 2021-12-07 14:09 UTC
