### ISSUE TITLE
Keep Connectivity Proxy independent from Kubernetes

### ISSUE THREAD

**Issue by franpog859** [kyma-incubator/reconciler#656] opened 2022-01-11 08:04 UTC
**Description**

Connectivity Proxy Reconciler should not use Secrets to obtain anything needed to work correctly (no access tokens in Secrets, no Pull Secrets, etc.)

**Reasons**

Reconciler should work not only in the Kubernetes environment. Being dependent on Secrets is against the Reconciler assumptions

---

Please, @clebs , enhance this issue with some insights about the Reconciler assumptions and possibly some suggestions on how to tackle this refactor

Feel free to take part in the discussion, brainstorm and propose a solution and create acceptance criteria below

I also know that @ralikio has some change requests to the Connectivity Proxy Reconciler. If you think it will fit in the topic of this issue, please, enhance it. If not, you can create a separate one

**Comment by clebs** [comment] 2022-01-11 08:39
Hi @franpog859,

thanks for creating this issue. As we discussed, the reconciler does not necessarily run on a K8s cluster and therefore it can't be assumed that its features will be available (as you mention: k8s API, secrets, etc...).

The reconciler should be able to run in any developer's computer, VM, container or cloud environment. Some already existing use cases for this are:
- Kyma CLI: runs reconciler locally on the same process as the CLI commands.
- CI/CD: Our pipelines run the reconciler on prow containers.

Having this in mind, custom reconcilers have to be configurable in an environment agnostic way (e.g. env vars, config files, programatically).

**Comment by tobiscr** [comment] 2022-01-11 08:49
We have to cleanup this part: credentials to external sources (GIT or HTACCESS or whatever) has to be passed as part of the KEB call, see https://github.com/kyma-incubator/reconciler/issues/418

**Comment by tobiscr** [comment] 2022-01-11 08:50
Will close this as duplicate of https://github.com/kyma-incubator/reconciler/issues/418

**Closed by tobiscr** 2022-01-11 08:50 UTC
Labels: area/reconciler
