### ISSUE TITLE
Upgrade from eval to prod profile fails on Kyma 2.0 with issue in PVC patching

### ISSUE THREAD

**Issue by raypinto** [kyma-incubator/reconciler#544] opened 2021-12-08 11:53 UTC
**Description**

When Kyma 2.0 is upgraded from evaluation to production profile, the upgrade fails for 3 components. Patching PVC seems to be causing the issue. 

`reason: cannot patch with kind PersistentVolumeClaim: PersistentVolumeClaim is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims`

**Expected result**

Upgrade succeeds

**Actual result**

3 components (serverless, monitoring and rafter) fail

**Steps to reproduce**

- Install Kyma 2.0 with evaluation profile (using latest reconciler)
- Upgrade Kyma 2.0 to production profile

**Troubleshooting**

3 components namely monitoring, rafter and serverless fail with the same issue:
```
cannot patch \"monitoring-grafana\" with kind PersistentVolumeClaim: PersistentVolumeClaim \"monitoring-grafana\" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims\n

cannot patch \"rafter-minio\" with kind PersistentVolumeClaim: PersistentVolumeClaim \"rafter-minio\" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims\n

cannot patch \"serverless-docker-registry\" with kind PersistentVolumeClaim: PersistentVolumeClaim \"serverless-docker-registry\" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims\n
```

**Comment by pbochynski** [comment] 2021-12-08 14:31
Switching profiles is not the main use case that's why I removed release blocker label.

**Comment by suleymanakbas91** [comment] 2021-12-13 09:00
Duplicate of https://github.com/kyma-incubator/reconciler/issues/557.

**Closed by suleymanakbas91** 2021-12-13 09:00 UTC
Labels: bug, area/reconciler
