### ISSUE TITLE
ORY reconciliation exceeds timeout

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#595] opened 2021-12-17 09:13 UTC
**Description**

After switching to Patch strategy, the ORY reconciliation exceeds the defined reconciliation timeout.

**Expected result**

ORY has to get reconciled within given time range.

**Actual result**

Time range exceeded and reconciliation gets stopped by reconciler.

**Steps to reproduce**

**Troubleshooting**

**Comment by raypinto** [comment] 2021-12-17 11:25
Tried the following and was not able to reproduce it:
- Install and reconcile with the evaluation profile using the latest reconciler
- Install and reconcile with the production profile using the latest reconciler
- Install kyma with cli (2.0) and reconcile with latest reconciler
- Install kyma with cli (latest stable) and reconcile with latest reconciler

**Comment by raypinto** [comment] 2021-12-17 13:07
I could reproduce the issue by upgrading 1.24.8 to 2.0. The issue seems to be caused because postgres was not bumped and the database was unstable.

```
2021-12-17 12:12:14.695 UTC [58] LOG:  incomplete startup packet
2021-12-17 12:12:15.777 UTC [60] ERROR:  relation "hydra_client_migration" does not exist at character 15
2021-12-17 12:12:15.777 UTC [60] STATEMENT:  SELECT * FROM hydra_client_migration
``` 

This is related to https://github.com/kyma-incubator/reconciler/issues/465 and may be fixed with the fix applied here.

**Comment by raypinto** [comment] 2021-12-17 15:04
@tobiscr are there any plans of getting statefulsets with PVC back into the reconciliation scope?

**Comment by tobiscr** [comment] 2021-12-17 15:48
Yes, there is: https://github.com/kyma-incubator/reconciler/pull/597 :)

**Comment by tobiscr** [comment] 2021-12-17 15:50
Tested it locally and ORY got working (took initally >4min, but worked finally).

Also reconciling SFS which include PVCs is now working without issues. PR for reconciling PVC and SFS with PVCs inside is open.

Finish last tests now, but looks promising. SFS image got also updated as expected when applying a PATCH for it (tested by changing Postgres image from 1.14.1 -> 1.13 -> 1.14.1)

**Comment by tobiscr** [comment] 2021-12-20 11:24
Control plane PR: https://github.com/kyma-project/control-plane/pull/1219

**Comment by tobiscr** [comment] 2021-12-22 16:28
Depends on #620

**Comment by veichtj** [comment] 2021-12-23 08:32
Timeout issue is fixed by this PR: https://github.com/kyma-project/test-infra/pull/4606

**Closed by veichtj** 2021-12-23 08:32 UTC
Labels: bug, required-for-kyma2.0, release blocker, prio1
