### ISSUE TITLE
CI/CD pipeline failed to install ORY component on Gardener cluster

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#772] opened 2022-02-04 08:02 UTC
**Description**

During the test execution we are facing issues in installing ORY on Gardener. The Problem happend just once now, but it would be helpful to verify if the issue is temporarily happening or seriuous.

Following pipelines reported issued in regards to ORY component or authentication:

* Authentication failed (looks like remote system is down and not caused by a component failure): https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2/1489479065751523328/build-log.txt
     
        1) Upgrade test tests
               function should be reachable through secured API Rule:
             Error: Error when requesting bearer token from https://oauth2.grdwb4m0f.kyma-prow.shoot.canary.k8s-hana.ondemand.com/oauth2/token: Error: connect ETIMEDOUT 20.93.40.170:443
              at OAuthToken.getToken (lib/oauth.js:71:17)

* ORY component could not be installed: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1489297869771902976/build-log.txt

        Deployed Components: 12/13
        Could not deploy the following components:
        - ory

**Expected result**

ORY installation and authentication is not failing during test execution.

**Actual result**

Fast integration test failed caused by either failing component installation of ORY or issues during the authentication flow.

**Steps to reproduce**

**Troubleshooting**

**Comment by piotrkpc** [comment] 2022-02-09 07:38
Unfortunately I cannot reproduce and confirm the issue.
- Regarding authentication failure I have tried many times and most of the job runs were successful - there were couple failures with installation of version 1.x due to timeout. (https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma-to-kyma2)
- Regarding installation of ory in the upgrade job from kyma2 to main. Again similar story, I was not able to reproduce this and most of the job run were successful https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-to-main. There were couple timeout errors recently however on `helm-broker` component (either in installation/upgrade phase or while waiting for test fixture). Examples: https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1490853670936383488/build-log.txt, https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main/1491109804196761600/build-log.txt
I was also trying to reproduce this issue manually and my observation is that GCP deployed Gardener performed slightly better then Azure deployed Gardener (installation time decreased by 3-7min) in most of the cases however the results are not 100%  consistent.

**Comment by varbanv** [comment] 2022-02-09 09:16
Pipelines are less flaky now so closing the ticket for now.

**Closed by varbanv** 2022-02-09 09:16 UTC
Labels: kind/bug, area/reconciler, release blocker, prio1
