### ISSUE TITLE
Remove cleaner component when reconciling a cluster

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#859] opened 2022-02-23 13:44 UTC
**Description**

The cleaner component has to be removed from a regular reconciliation run because it's causing a higher amount of load in productive systems and slowing down the processing time as it's another sequential step in the reconciliation process.

AC:
- Operation step for `cleaner` should only be executed when a cluster gets deleted
- The `cleaner` should only be called when a deletion of a cluster is happening

**Expected result**

No `cleaner` component is called during a reconciliation. It is only called when a cluster gets deleted.

**Actual result**

The component `cleaner` is also callend when a normal (no-deletion) reconciliation is happening.

**Steps to reproduce**

**Troubleshooting**

**Comment by clebs** [comment] 2022-02-28 09:43
Duplicate of #715

**Closed by clebs** 2022-02-28 09:43 UTC
Labels: kind/feature, area/reconciler, sre-relevant, prio1
