### ISSUE TITLE
WorkerPool cannot release resources if GitHub API request failed

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-incubator/reconciler#1098] opened 2022-05-27 16:28 UTC
**Description**
Recently GitHub had an outage ([history link](https://www.githubstatus.com/incidents/zhtplv7zd052)). Thus, the API was not reachable and we got the following errors on several component reconcilers:

```
"Failed to get CRD manifests for Kyma version '2.2.0': Error downloading Git repository (https://github.com/kyma-incubator/sap-btp-service-operator/releases/download/v0.2.5/  sap-btp-operator-v0.2.5-low-cpu-req.tgz): Failed to clone the repository: 'repository not found': repository not found","correlation-id":"9c253db2-946e-4134-ac32-3e04a624b2a3--52bc9f2a-f54e-4793-ac3b-be5c7b20ac7b","component-name":"CR ││ Ds"}
```

Then the worker was not able to release the resources and got stuck. This happened then for all workers and the workerpool was fully occupied without releasing any resource.

**Expected result**
In such case worker should release resource to fetch new work, and thus those request will be retried.

**Actual result**
Worker pool was fully occupied and got stuck.

**ACs**
- Investigate why worker was is not able to release resources in such scenario
- Find an applicable solution that the worker will be rescheduled and fetched new work (thus, the API request will be retried automatically, without the need to restart the reconciler)

**Comment by tobiscr** [comment] 2022-05-30 19:55
Each component reconciler is retrying 5 times (with expotential delay between the retries) until it gives finally up. In error cases like this, each component-reconciler which tries to talk to Github (means, nearly all component reconciler we have!) will fail and retry the failing task after a waiting period.

This will quite fast also lead to a worker pool saturation as any worker is taking much longer as usual to process his task (caused by the retries).

We were thinking of introducuing a fail-fast feature which let the worker direclty stop the processing if an error is not recoverable. But caused by the prio shift to convert the reconciler into a K8s native app, we moved this feature down in our backlog (see https://github.com/kyma-incubator/reconciler/issues/257).

**Comment by tobiscr** [comment] 2022-05-30 20:16
Duplicate of https://github.com/kyma-incubator/reconciler/issues/257

**Closed** 2022-05-30 20:17 UTC
Labels: area/reconciler, prio1
